# Compose fileのバージョン指定
version: '3'

# どんなコンテナを立ち上げるか
services:

 # ---------------------------------
 # 動かすコンテナ
 # ---------------------------------
 app:
   # どのポートを開いて繋ぐか。下記はコンテナの80番ポートを開いて、ホストの8080番につなぐ
   # Window10の環境では既に80番ポートが埋まっている場合があるので
   ports:
     - "8079:79"
     - "8080:80"
     - "8081:81"
     - "8082:82"
   # 先ほど作ったDockerfileを使って、コンテナをビルドするという指定
   build: ./docker/app
   # コンテナの名前を指定
   container_name: js_batch_prod
   # ローカルのディレクトリとコンテナ上のディレクトリのリンクを設定
   # コンテナが作成されると src ディレクトリからコンテナの /var/www/html にアクセスすることができる
   volumes:
     - ../../prod_batch_test:/var/www/html
